### ISSUE TITLE
Why not use Vec::split_off?

### ISSUE THREAD

**Issue by rokob** [discordapp/sorted_set_nif#1]
It looks like this function:

https://github.com/discordapp/sorted_set_nif/blob/4e023e121ee309ef46584e2dcbb8249a52fbd2a8/native/sorted_set_nif/src/bucket.rs#L27-L47

is just copied from std:

https://doc.rust-lang.org/src/alloc/vec.rs.html#1233-1249

Is there some particular reason for that? It is the only use of unsafe and seems to be unnecessary.

**Comment by hayd** [comment]
suggestion on [reddit](https://www.reddit.com/r/rust/comments/bpw1aw/using_rust_to_scale_elixir_for_11_million/enz60k5/):
```rust
pub fn split(&mut self) -> Bucket {
    let at = self.data.len() / 2;
    let mut other = self.data.split_off(at);
    other.reserve_exact(at);
    Bucket { data: other }
}
```

**Comment by jhgg** [comment]
The reason is to allocate the target vector at the correct capacity, libstd's allocates it at the size of the split. We know we're going to immediately grow it, so we allocate it at the correct size. 

It would be possible to allocate -> reserve, however, that introduces a potential re-allocation which we wanted to avoid.
